### PR TITLE
Fix instance TestData Float/Double

### LINKED ISSUE #460: Tests fail when built against QuickCheck-2.14.3
```
Test suite vector-tests-O2: RUNNING...
toplevel
  Tests.Vector.Unboxed
    (Float)
      product:                                   FAIL
        *** Failed! Falsified (after 60 tests):
        [32.0,-18.487179,-46.0,4.0,1.3333334,-0.33333334,-19.0,-32.022728,1.6666666,0.4007722,45.192307,0.375,-49.0,45.210526,27.458334,16.0,33.97059,-18.466667,57.939392,-40.0,-18.0,0.81411356,-7.0,-9.222222,-0.25,-17.0,31.85965,-0.5714286,58.6,-38.01695,0.2850433,6.1225712e-2,0.75,46.0,19.666666,-13.0,-0.3773585,18.5,20.0,0.8629303,0.7045016,18.458334,0.18349916,1.125,32.06,-41.757576,-47.0,20.8,-31.714285,-41.363636,-11.896552,0.0,-19.0]
        NaN /= NaN
        Use --quickcheck-replay=745456 to reproduce.
        Use -p '/(Float).product/' to rerun this test only.
```

### PR DESCRIPTION
**Pull request by Bodigrim**
Fixes #460.

### CODE REVIEW

File: vector/tests/Utilities.hs [hunk 1]
```diff
@@ -121,10 +121,24 @@ instance TestData ty where { \
...
-id_TestData(Double)
 id_TestData(Ordering)
 
+instance TestData Float where
+  type Model Float = Float
+  model = id
+  unmodel = id
+
+  type EqTest Float = Property
+  equal x y = property (x == y || isNaN x == isNaN y)
```
Comment (konsumlamm) [inline vector/tests/Utilities.hs:132]:
```suggestion
  equal x y = property (x == y || (isNaN x && isNaN y))
```
With your definition, every non-NaN number is equal to every other non-NaN number.

File: vector/tests/Utilities.hs [hunk 2]
```diff
@@ -121,10 +121,24 @@ instance TestData ty where { \
...
+
+instance TestData Double where
+  type Model Double = Double
+  model = id
+  unmodel = id
+
+  type EqTest Double = Property
+  equal x y = property (x == y || isNaN x == isNaN y)
```
Comment (konsumlamm) [inline vector/tests/Utilities.hs:140]:
```suggestion
  equal x y = property (x == y || (isNaN x && isNaN y))
```

File: vector/tests/Utilities.hs (hunk 1 above)
Comment (Bodigrim) [reply vector/tests/Utilities.hs]: Thanks a lot!

**Review by lehins — APPROVED** [review]
Looks good. Thank you for fixing it
